### ISSUE TITLE
how do I access the angular app files

### ISSUE THREAD

**Issue by aevanson** [Karnith/sails-generate-angular-gws#14]
I've followed the proper steps (AFAIK)... sails lift runs OK but I get the default sails page at http://localhost:1337/. I've tried going to http://localhost:1337/app/ but it says page not found.

**Comment by Karnith** [comment]
Yep, that is correct. You need to go to http://localhost to see the angular page ;)

This module adds gulp web server so that sails is on port 1337, for the api, while the angular app is on port 80.

**Comment by aevanson** [comment]
Ok, that makes sense. I'm not sure if the gulp web server is even loading actually. I am getting an error after lifting sails in the terminal. It shows up after a few seconds underneath the sailboat. Any idea what this could be?

error: Gulp :: events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1112:19)
  at listen (net.js:1155:10)
  at net.js:1253:9
  at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:81:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:99:10)

**Comment by aevanson** [comment]
Solved my own problem I think. Seems like running sudo sails lift does the trick. Not sure if there's a better way though.

**Comment by aevanson** [comment]
Ugh. Not quite there yet. I can see the angular app now but not all of pages are working properly and I'm getting a flow of errors in the console like this:

XMLHttpRequest cannot load http://localhost:1337/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_s…sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1431651646448-3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
sails.io.js:143  
        Socket is trying to reconnect to Sails...
_-|>_\-  (attempt #4)

**Comment by Karnith** [comment]
Yeah, socket.io currently has issues.

-------- Original message --------

**Comment by Karnith** [comment]
socket.io has been fixed. Add the following to the bower file, for now, until I have time to update the generator.

"sails.io.js": {
      "ignore": [
        "./**/sails.io.js"
      ]
    },

I would also update all the generators by uninstalling them globally and reinstalling them using Karnith/{git_repo_name} until I publish all the changes I've done.
